# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aba7451aafaaf1726f58f3e9ce7c099e7bd0853d005cc51543df2445340e952764f1997df50accdf0e50e527bb1c9302fcbf1aaed549ce94cf98bf187303448

test:
  secret_key_base: b86d1578c8ec8d0fdda9e2ea1584ed36c52061ce0163ccc6f85ac02ad7d1b955369970b42a9e1ff71b7918e73dba9b807a3ff1f141f1ddefa33581e4fb32d60e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
